language: bash
install:
  - pip install --target=. Alfred-Workflow
script:
  - git describe --abbrev=0 > version
  - zip  -r yandex.translate.alfredworkflow . -x "*.git*"
deploy:
  provider: releases
  api_key:
    secure: b3/KK+z6Q2mLufsOpRb2MlV5hT54ZdTovMTRi0eqn5xYupDLoQgLEOnRxpmFyR9H0t8a1DvJ9f2gl/WUYkAOXe8Koe3p8WKQLeBrOFdP/QGvlK51tdg8/qcfmWMf4clbvH7MGMiFgQ62GnqCcg1e/JATdHe81S1KjIJ4M1Hky2tNoHCvtaacRurNK3+2ho+tJqdB/DRQ4BhmaO/bw4lzN0sjSrWpWHqcum4iCfx5ZcbQiF1SH+1cNJzY78JGxtsIpMK8ZYa1Ot4+vbmSDDcB9Cg5DSenPEa/MP+p2RSXNzHqOtEh51rWXrUrwFdXht+3T3HCX5WdJS0fGzxYrfDBAYUA/XL5AYrx57Q5PzX0Aoriu4NcIEaVYTL9OibYj207XS3OzhAvX9oyYFGsjhDwjmJ4Dgsn3Rbb6KqwI07Tkew4QqfAG27savBuEuH8+MMU7LObkDPVKvgxPCHIM2XAxENhhP3qpxT0eRFt/sJxZDwd1f7zF28T3TbYavz6NIB5EcXoRFEMhenuMa5vSXZ7Zmp7uOzC6Y5/JFog5DzA82mGEq4Rpvf/uco6IeDeLA8gBujwrRjMoN16kcwoADYpTrSHON3ZTzOOGLBSgMOKTU/Ss1jeWJP0U6rqDGnoUMMkhcXO0vkQFMbmQx1UoLG5//P1Kt+JLpyDnfqzvguQE/s=
  file: yandex.translate.alfredworkflow
  skip_cleanup: true
  on:
    tags: true
    repo: Pr0Ger/alfred_yandex.translate
